Aspnet.Jquery.Ajax/Models/Category.cs
namespace Aspnet.Jquery.Ajax.Models
{
    public class Category
    {
        public string CategoryID { get; set; }
        public string CategoryName { get; set; }
    }
}

Aspnet.Jquery.Ajax/Models/UnregStaffVM.cs
namespace Aspnet.Jquery.Ajax.Models
{
    public class UnregStaffVM
    {
        public string? userId { get; set; }
        public int? ModuleId { get; set; }
        public string? role { get; set; }
    }
}

Aspnet.Jquery.Ajax/Areas/ContentType/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Aspnet.Jquery.Ajax.Area.ContentType.Controllers
{
    [Area("ContentType")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult IndexForm(DataRequest dataRequest)
        {
            var request = Request;
            return Json(new { test = "hello" });
        }
        [HttpPost]
        public IActionResult IndexBody([FromBody] DataRequest dataRequest)
        {
            var request = Request;
            return Json(new { test = "hello" });
        }

        public record DataRequest(string userId, string ModuleId, string role);
    }
}

Aspnet.Jquery.Ajax/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Aspnet.Jquery.Ajax.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Aspnet.Jquery.Ajax/Controllers/ListboxWithModelController.cs
using Aspnet.Jquery.Ajax.Models;
using Microsoft.AspNetCore.Mvc;

namespace Aspnet.Jquery.Ajax.Controllers
{
    public class ListboxWithModelController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public JsonResult GetCategoriesWithModel()
        {
            List<Category> lstCateogories = new List<Category>();
            lstCateogories.Add(new Category() { CategoryID = "1", CategoryName = "Beverages" });
            lstCateogories.Add(new Category() { CategoryID = "2", CategoryName = "Condiments" });
            lstCateogories.Add(new Category() { CategoryID = "3", CategoryName = "Confections" });
            lstCateogories.Add(new Category() { CategoryID = "4", CategoryName = "Dairy Products" });
            lstCateogories.Add(new Category() { CategoryID = "5", CategoryName = "Grains/Cereals" });
            lstCateogories.Add(new Category() { CategoryID = "6", CategoryName = "Meat/Poultry" });
            lstCateogories.Add(new Category() { CategoryID = "7", CategoryName = "Produce" });
            lstCateogories.Add(new Category() { CategoryID = "8", CategoryName = "Seafood" });

            return Json(lstCateogories);
        }
    }
}

Aspnet.Jquery.Ajax/Controllers/PopulateListBoxController.cs
using Microsoft.AspNetCore.Mvc;

namespace Aspnet.Jquery.Ajax.Controllers
{
    public class PopulateListBoxController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public JsonResult GetCategories()
        {
            Dictionary<string, string> lstCategories = new Dictionary<string, string>();
            lstCategories.Add("1", "Beverages");
            lstCategories.Add("2", "Condiments");
            lstCategories.Add("3", "Confections");
            lstCategories.Add("4", "Dairy Products");
            lstCategories.Add("5", "Grains/Cereals");
            lstCategories.Add("6", "Meat/Poultry");
            lstCategories.Add("7", "Produce");
            lstCategories.Add("8", "Seafood");
            return Json(lstCategories);
        }
    }
}

Aspnet.Jquery.Ajax/Views/PopulateListBox/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="margin:25px;">
    <div>
        <h2>Fill MVC ListBox using jQuery getJSON and JSONResult</h2>
    </div>
    <div>
        <b>Categories</b>
    </div>
    <div>
        @*@Html.ListBox("Categories", new SelectList(new[] { "" }),
        new { @class = "list-group", @style = "width: 150px; height:150px; margin:15px;" })*@
        <select class="list-group" id="Categories" multiple="multiple" name="Categories" style="width: 150px; height:150px; margin:15px;">
        </select>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            $.getJSON('PopulateListBox/GetCategories/', function (data) {

                //clear the current content of the select
                $('#Categories').empty();

                //iterate over the data and append a select option
                $.each(data, function (key, val) {
                    $('#Categories').append('<option id="' + key + '">' + val + '></option>');
                })
            });
        });
    </script>
}

Aspnet.Jquery.Ajax/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Razor Pages</title>
    <link href="~/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="~/jqueryui/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/data-tables/jquery.datatables.min.css" rel="stylesheet" />
    <link href="~/data-tables/select.datatables.min.css" rel="stylesheet" />
</head>
<body>
    <style>
        .max-button{
            width: 200px
        }
    </style>
    <div class="row m-1 p-1">
        <div id="categories" class="col-2">
            <div class="btn-group" name="examples1">
                <button class="btn btn-secondary btn-lg max-button" type="button">
                    MVC
                </button>
                <button type="button" class="btn btn-lg btn-secondary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                </button>
                <div class="dropdown-menu">
                    <a class="btn btn-secondary" asp-action="Index" asp-controller="PopulateListBox">
                        Populate ListBox
                    </a>
                    <a class="btn btn-secondary" asp-action="Index" asp-controller="ListboxWithModel">
                        Listbox With Model
                    </a>
                </div>
            </div>
            <div class="btn-group" id="examples2">
                <button class="btn btn-secondary btn-lg max-button" type="button">
                    MVC with areas
                </button>
                <button type="button" class="btn btn-lg btn-secondary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                </button>
                <div class="dropdown-menu">
                    <a class="btn btn-secondary" href="/ContentType/Home/index">
                        Ajax Post JSON
                    </a>
                </div>
            </div>
            <div class="btn-group" id="examples3">
                <button class="btn btn-secondary btn-lg max-button" type="button">
                    RAZOR pages
                </button>
                <button type="button" class="btn btn-lg btn-secondary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                </button>
                <div class="dropdown-menu">
                    <a class="btn btn-secondary" href="/ajax_post/example_01/ContentType">
                        Ajax Post Form
                    </a>
                    
                </div>
            </div>
        </div>
        <div class="col-10">
            @RenderBody()
        </div>
        <div id="_SiteScripts" class="hidden">
            <script src="~/jquery/jquery.min.js"></script>
            <script src="~/bootstrap/popper.min.js"></script>
            <script src="~/bootstrap/bootstrap.min.js"></script>
            <script src="~/jqueryui/jquery-ui.min.js"></script>
            <script src="~/data-tables/jquery.datatables.min.js"></script>
            <script src="~/data-tables/datatables.select.min.js"></script>
            <script src="~/jquery/jquery.validate.min.js"></script>
            <script src="~/jquery/jquery.unobtrusive-ajax.min.js"></script>
        </div>
        @await RenderSectionAsync("Scripts", required: false)
    </div>
</body>
</html>